// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExpenseTracker.Api.Models;

public partial class Category
{
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual User User { get; set; }
}