// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExpenseTracker.Api.Models;

public partial class Transaction
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid AccountId { get; set; }

    public Guid CategoryId { get; set; }

    public decimal Amount { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Category Category { get; set; }

    public virtual User User { get; set; }
}